// <auto-generated />
namespace Yoox.Commerce.Dal.TeamB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StrutturaIniziale : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StrutturaIniziale));
        
        string IMigrationMetadata.Id
        {
            get { return "201609261402186_StrutturaIniziale"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
